
- name: bring down global requirements
  git: 
    repo: "{{ requirements_repo }}"
    dest: "{{ requirements_dir }}"
    version: "{{ requirements_branch }}"
    accept_hostkey: yes

- name: Install pbr
  git:
    repo: "{{ pbr_repo }}"
    dest: "{{ dest }}/pbr"
    version: "{{ pbr_branch }}"
    accept_hostkey: yes

# OR
#  pip:
#    name: pbr
